---
title: "GARCH Basics"
author: "Tyler Binning"
format: html
date: "2025-03-6"
categories: [Time Series, Predictive Modeling]
---

# What is GARCH?

G.A.R.C.H. stands for: Generalized AutoRegressive COnditional Heteroskedasticity. 
GARCH is used to help predict teh volatility of returns on financial assets. 
This model helps analyze time-series data where the variance error is believed to be serially autocorrelated. 

Firms use the resulting information to help determine pricing and judge which assets will potentially provide higher returns, as well as to forecast the returns of current investments to help in their asset allocation, hedging, risk management, and portfolio optimization decisions.

Fixes problems regarding to heteroskedasticity. 

This means that it is a function of an average of its own past values.

# Extra Info
Built upon ARCH:
AutoRegressive Conditional Heteroskedasticity. 
Assumes financial returns over time were not constant over time but autocorrelated, or conditional dependent on each other. 

This demonstrated in stock returns where periods of volatility in returns tend to be clustered together.

- NGARCH: addresses correlation
- IGARCH: restricts the volatitlity parameter

- GARCH models are viewed to provide better gauges of risk than standard deviation alone

ARCH is a model used to analyze historical volatility in norder to predict future volatility. 
GARCH is an extenstion of ARCH model that allows for variance in the error term.

Heteroskedasticity: when the error term changes over time. 



