project:
  type: website
  output-dir: docs

website:
  title: "Algorithmic Trading Blog"
  navbar:
    right:
      - about.qmd
      - QRintro.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/tyler-r-binning/
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme: pulse
    css: styles.css



