project:
  type: website
  output-dir: docs
  theme: pulse 
  
website:
  title: "Algorithmic Trading Bot"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css



