---
title: "Evaluating Congress Members Stock Reports"
author: "Tyler Binning"
format: html
date: "2025-02-19"
categories: [Trading]
---

# Background

Many of Senators or Representatives have inside knowledge of bills that will be passed indicating potentional price changes for stocks in different industries. 

From the recent popularity making certain politicians infamous for what is pretty much insider trading there have been bots/ apps created to invest automatically for you based off of different politicians needs. One important detail is that members of congress have 48 hours to file these reports.

The basis of this study isn't to gain value off of the price due to policy, but more so a larger focus on the surge of mindless bots that buy stocks off of the decision of a politician. 

This analysis is also to detail whether there is a connection between volume and price increase as compared to the overall increase due to policy change, is there a disconnect? Or would it be better to join the herd?

# Autopilot

